title:              Anaïs Andos
email:              anais.andos@gmail.com
phone:              0666377940
description:        Rédactrice indépendante
author:             Anaïs Andos

# Third party services
formspree_endpoint: https://formspree.io/f/mlezderd
google_analytics:   G-0EKZ23M3G5

# Build settings
markdown:           kramdown

# Plugins
plugins:
  - jekyll-sitemap

# Collections
collections:
  - projects
  - testimonials

defaults:
  -
    scope:
      path: ""
    values:
      background: '/img/background.jpg'

