site_title: Anais Andos
site_subheader: Rédactrice indépendante
site_description: Mon souhait ? Ecrire, écrire et écrire encore pour prendre
  soin de demain dès aujourd’hui.
links:
  - type: email
    value: anais.andos@gmail.com
  - type: phone
    value: "0666377940"
  - type: linkedin
    value: anaïs-andos-49104b1bb
