backend:
  name: git-gateway
  branch: main

local_backend: true

media_folder: "img"

collections:
  # Projects & Clients
  - name: "projects"
    label: "Projets"
    label_singular: "Projet"
    identifier_field: client
    summary: '{{client}} – {{title}}'
    sortable_fields: [ 'client' ]
    folder: "_projects"
    create: true
    slug: "{{client}}"
    media_folder: '/img/projects'
    fields:
      - {label: "Client", name: "client", widget: "string"}
      - {label: "Titre", name: "title", widget: "string", required: false}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Lien", name: "link", widget: "string", required: false}
      - {label: "Bouton", name: "cta", widget: "string", default: "En lire plus", required: false}
      - label: "Image"
        name: "image"
        widget: "image"
        default: "/img/projects/default.jpg"
        hint: "Dimensions: 535x310, format: jpg"
        choose_url: false
        media_library:
          config:
            multiple: false
            
  # Testimonials
  - name: "testimonials"
    label: "Témoignages"
    label_singular: "Témoignage"
    identifier_field: author_name
    folder: "_testimonials"
    create: true
    fields:
      - {label: "Client", name: "author_name", widget: "string"}
      - {label: "Titre du client", name: "author_title", widget: "string"}
      - {label: "Lien", name: "link", widget: "string", required: false}
      - {label: "Témoignage", name: "body", widget: "markdown"}

# Pages
  - label: "Pages"
    name: "pages"
    files:
      # Contact
      - label: "Contact"
        name: "contact"
        file: "contact.html"
        editor:
          preview: false
        fields:
          - {label: "Titre SEO", name: "title", widget: "string"}
          - {label: "Description SEO", name: "description", widget: "text"}
          - {label: "Titre de la page", name: "heading", widget: "string"}
          - {label: "Introduction", name: "intro", widget: "markdown"}

# Settings
  - label: Configuration
    name: settings
    files:
      - label: General
        name: global
        file: "_data/settings.yml"
        editor:
          preview: false
        fields:
          - {label: "Titre du site", name: "site_title", widget: "string"}
          - {label: "Sous-titre du site", name: "site_subheader", widget: "string"}
          - {label: "Description SEO du site", name: "site_description", widget: "text", hint: "Apparait dans les resultats de moteur de recherche ou quand la page d'acceuil est partagee sur les reseaux sociaux."}
          - label: Liens
            label_singular: Lien
            name: links
            widget: list
            summary: '{{type}}'
            collapsed: false
            fields:
              - label: Type
                name: type
                widget: select
                options:
                  - { label: "Email", value: "email" }
                  - { label: "Telephone", value: "phone" }
                  - { label: "Twitter", value: "twitter" }
                  - { label: "Facebook", value: "facebook" }
                  - { label: "LinkedIn", value: "linkedin" }
                  - { label: "Instagram", value: "instagram" }
              - { label: Lien, name: value, widget: string }